"""Close the holes luau-lsp cannot see, before generated Luau is accepted.

luau-lsp does not type-check anything reached through the `game` global: with a
sourcemap, `game:TotallyMadeUpMethod()` is accepted and fails at run time, while
the same mistake on a typed value is rejected. A model that hallucinates a
service method would therefore pass every check.

The fix is structural rather than heuristic. `game` (and every other route to
an untyped DataModel) is forbidden in generated code. Services are reached
through one generated module, `Services.luau`, which is the only file allowed
to touch `game`, and which casts each service to its concrete class on the way
out. Every call on a service then lands on a typed value that luau-lsp checks.
The module must be byte-identical to what `render_services_module` produces,
so a model cannot edit it into a back door.

This works on tokens, not a parse tree. Comments and strings -- including the
code inside interpolated strings -- are handled exactly, which is what decides
whether a `game` is really the global.
"""

from __future__ import annotations

import bisect
import re
from dataclasses import dataclass
from pathlib import Path

# Globals that reach the DataModel untyped, or reach code the checker cannot
# see. Each message says what to write instead, because it is fed back to the
# model that wrote the violation.
FORBIDDEN_GLOBALS: dict[str, str] = {
    "game": "`game` is not type-checked; get services from the Services module",
    "Game": "deprecated alias of `game`; get services from the Services module",
    "workspace": "use Services.Workspace, which is type-checked",
    "Workspace": "deprecated global; use Services.Workspace",
    "getfenv": "environment access defeats every static check",
    "setfenv": "environment access defeats every static check",
    "loadstring": "runtime code cannot be checked",
    "_G": "shared global tables are untyped; require a module instead",
    "shared": "shared global tables are untyped; require a module instead",
}

# `script` is a sourcemap node, not a typed value, so nothing reached from it is
# checked. Both of these were accepted by luau-lsp on the real toolchain:
#
#     script:FindFirstAncestorWhichIsA("DataModel"):MadeUp()
#     script.Parent:MadeUp()   /   script.Parent.NotARealChild
#
# They are the same hole as `game`, reached without naming it. What makes the
# ban narrow rather than sweeping is that the methods themselves are fine: from
# a *typed* receiver, luau-lsp rejects all of
#
#     Services.Players:FindFirstAncestorWhichIsA("DataModel"):MadeUp()
#     Services.Workspace.Parent:MadeUp()
#     Services.Workspace:FindFirstChild("Thing"):MadeUp()
#     local s: Instance = script ; s:MadeUp()
#
# -- the last one catching `MadeUp` on `DataModel` itself. Only the bare global
# is untyped, so only the bare global is banned.
#
# An annotated local (`local s: Instance = script`) is type-safe too, and is
# deliberately still refused. Admitting it would mean reading the annotation,
# and `local s: any = script` passes that reading while restoring the hole in
# full. The ban stays where it can be decided from the token stream alone.
SCRIPT_GLOBAL = "script"
# Rojo maps src/client to StarterPlayer.StarterPlayerScripts.Client, and at run
# time Roblox COPIES StarterPlayerScripts into Player.PlayerScripts. Inside that
# copied folder relative depth is preserved, so `script.Parent.Sibling` is the
# same instance in Studio and in a live game. One step further up is not: in the
# sourcemap it is StarterPlayerScripts, in a live game it is PlayerScripts, and
# above that the trees diverge entirely (Player, Players, DataModel against
# StarterPlayer, DataModel). luau-lsp resolves against the sourcemap, so a
# require that walks out of the client folder type-checks against a tree that
# will not exist when it runs.
CLIENT_ROOT = "src/client/"
CLIENT_REQUIRE_MESSAGE = (
    "a client require may not reach above its own folder: client scripts are copied into "
    "Player.PlayerScripts at run time, so anything above them is a different tree than the one "
    "luau-lsp checked. Require siblings (`require(script.Parent.Thing)`) and reach services "
    "through the generated client Services module."
)
SCRIPT_MESSAGE = (
    "`script` is a sourcemap node, so nothing reached from it is type-checked; "
    "it is allowed only as `require(script.Parent.X)` -- reach instances through "
    "a typed value instead, such as the Services module"
)

# An entry point is not a module: Rojo makes it a Script, Roblox runs it, and
# the folder of modules it starts is its own parent. `script.Parent` is the
# only way in, so the `script` ban is relaxed there -- and only that far.
ENTRY_SCRIPT = (".server.luau", ".client.luau")

STRICT_HEADER = "--!strict"
SERVICES_HEADER = (
    "--!strict\n"
    "-- Generated by roblox-venture-agents (app/engineer/luau_guard.py). Do not edit:\n"
    "-- the gate rejects any version of this file the generator would not produce.\n"
    "-- `game` is not type-checked, so this is the only file allowed to touch it.\n"
    "-- Each service leaves here cast to its concrete class, so calls on it are checked.\n"
)
_SERVICE_LINE = re.compile(r'^\t([A-Za-z_]\w*) = game:GetService\("([A-Za-z_]\w*)"\) :: ([A-Za-z_]\w*),$')
# The DataModel is not a service -- `game:GetService("DataModel")` does not
# exist -- so it is reached by casting `game` itself and has its own line
# shape. See `render_services_module` for why it is allowed at all.
DATAMODEL_NAME = "DataModel"
_DATAMODEL_LINE = re.compile(r'^\t(DataModel) = game :: DataModel,$')
_MULTI_CHAR_OPERATORS = ("...", "..", "::", "==", "~=", "<=", ">=", "->", "//")


class LuauSyntaxError(ValueError):
    pass


@dataclass(frozen=True)
class Token:
    kind: str  # "name", "number", "string", "op"
    text: str
    offset: int


@dataclass(frozen=True)
class Violation:
    path: str
    line: int
    column: int
    rule: str
    message: str

    def __str__(self) -> str:
        return f"{self.path}:{self.line}:{self.column}: [{self.rule}] {self.message}"


def _long_bracket_level(source: str, i: int) -> int | None:
    """`[[`, `[=[`, `[==[`... at `i` -> its level; anything else -> None."""
    if i >= len(source) or source[i] != "[":
        return None
    j = i + 1
    while j < len(source) and source[j] == "=":
        j += 1
    return j - i - 1 if j < len(source) and source[j] == "[" else None


def _skip_long_bracket(source: str, i: int, level: int) -> int:
    close = "]" + "=" * level + "]"
    end = source.find(close, i + level + 2)
    if end == -1:
        raise LuauSyntaxError(f"unterminated long bracket at offset {i}")
    return end + len(close)


def _skip_quoted(source: str, i: int) -> int:
    quote = source[i]
    j = i + 1
    while j < len(source):
        c = source[j]
        if c == "\\":
            j += 2
            continue
        if c == quote:
            return j + 1
        if c == "\n":
            break
        j += 1
    raise LuauSyntaxError(f"unterminated string at offset {i}")


def _scan_interpolated(source: str, i: int, stack: list[int]) -> int:
    """Scan string text from `i` until the closing backtick or an opening `{`.

    On `{` an expression begins: a depth counter is pushed and control returns
    to code mode, so names inside `{...}` are tokenized like any other code.
    """
    j = i
    while j < len(source):
        c = source[j]
        if c == "\\":
            j += 2
            continue
        if c == "`":
            return j + 1
        if c == "{":
            stack.append(0)
            return j + 1
        if c == "\n":
            break
        j += 1
    raise LuauSyntaxError(f"unterminated interpolated string near offset {i}")


def tokenize(source: str) -> list[Token]:
    tokens: list[Token] = []
    interpolation: list[int] = []  # brace depth inside each open `{...}`
    i, n = 0, len(source)
    while i < n:
        c = source[i]
        if c.isspace():
            i += 1
        elif source.startswith("--", i):
            level = _long_bracket_level(source, i + 2)
            if level is not None:
                i = _skip_long_bracket(source, i + 2, level)
            else:
                newline = source.find("\n", i)
                i = n if newline == -1 else newline
        elif c == "[" and _long_bracket_level(source, i) is not None:
            end = _skip_long_bracket(source, i, _long_bracket_level(source, i))
            tokens.append(Token("string", source[i:end], i))
            i = end
        elif c in "\"'":
            end = _skip_quoted(source, i)
            tokens.append(Token("string", source[i:end], i))
            i = end
        elif c == "`":
            tokens.append(Token("string", "`", i))
            i = _scan_interpolated(source, i + 1, interpolation)
        elif c == "}" and interpolation and interpolation[-1] == 0:
            interpolation.pop()
            i = _scan_interpolated(source, i + 1, interpolation)
        elif c.isdigit() or (c == "." and i + 1 < n and source[i + 1].isdigit()):
            j = i + 1
            while j < n and (source[j].isalnum() or source[j] in "._"
                             or (source[j] in "+-" and source[j - 1] in "eE" and not source.startswith(("0x", "0X"), i))):
                j += 1
            tokens.append(Token("number", source[i:j], i))
            i = j
        elif c.isascii() and (c.isalpha() or c == "_"):
            j = i + 1
            while j < n and source[j].isascii() and (source[j].isalnum() or source[j] == "_"):
                j += 1
            tokens.append(Token("name", source[i:j], i))
            i = j
        else:
            op = next((o for o in _MULTI_CHAR_OPERATORS if source.startswith(o, i)), c)
            if interpolation and op == "{":
                interpolation[-1] += 1
            elif interpolation and op == "}":
                interpolation[-1] -= 1
            tokens.append(Token("op", op, i))
            i += len(op)
    if interpolation:
        raise LuauSyntaxError("unterminated interpolated string expression")
    return tokens


def _position(source: str, offset: int) -> tuple[int, int]:
    starts = [0] + [m.end() for m in re.finditer("\n", source)]
    line = bisect.bisect_right(starts, offset)
    return line, offset - starts[line - 1] + 1


def require_spans(tokens: list[Token]) -> list[range]:
    """One range of token indices per `require(...)` argument list.

    Separate from `require_argument_span`, which merges every argument into one
    set: a per-require range is what lets a rule count something inside a single
    require without a second require in the same file changing the answer.
    """
    spans: list[range] = []
    for index, token in enumerate(tokens):
        if token.kind != "name" or token.text != "require":
            continue
        previous = tokens[index - 1] if index else None
        if previous is not None and previous.kind == "op" and previous.text in (".", ":"):
            continue
        if index + 1 >= len(tokens) or tokens[index + 1].text != "(":
            continue
        depth = 0
        for position in range(index + 1, len(tokens)):
            text = tokens[position].text
            if tokens[position].kind == "op" and text == "(":
                depth += 1
            elif tokens[position].kind == "op" and text == ")":
                depth -= 1
                if depth == 0:
                    spans.append(range(index + 2, position))
                    break
    return spans


def check_source(source: str, path: str) -> list[Violation]:
    """Violations in one generated file (not the Services module)."""
    def violation(offset: int, rule: str, message: str) -> Violation:
        line, column = _position(source, offset)
        return Violation(path, line, column, rule, message)

    def require_argument_span(tokens: list[Token]) -> set[int]:
        """Token indices inside the parentheses of a `require(...)` call.

        `require(script.Parent.Services)` is the only way to reach the Services
        module, so the `script` ban has to leave it alone. Spans are matched by
        counting parentheses rather than by regex, so a nested call inside the
        argument does not end the span early.
        """
        inside: set[int] = set()
        for index, token in enumerate(tokens):
            if token.kind != "name" or token.text != "require":
                continue
            previous = tokens[index - 1] if index else None
            if previous is not None and previous.kind == "op" and previous.text in (".", ":"):
                continue  # a field named `require`, not the global
            if index + 1 >= len(tokens) or tokens[index + 1].text != "(":
                continue
            depth = 0
            for position in range(index + 1, len(tokens)):
                text = tokens[position].text
                if tokens[position].kind == "op" and text == "(":
                    depth += 1
                elif tokens[position].kind == "op" and text == ")":
                    depth -= 1
                    if depth == 0:
                        break
                else:
                    inside.add(position)
        return inside

    found: list[Violation] = []
    if source.split("\n", 1)[0].strip() != STRICT_HEADER:
        found.append(Violation(path, 1, 1, "strict-mode",
                               f"first line must be `{STRICT_HEADER}`; non-strict mode hides type errors"))
    try:
        tokens = tokenize(source)
    except LuauSyntaxError as exc:
        return [*found, Violation(path, 1, 1, "syntax", str(exc))]

    in_require = require_argument_span(tokens)
    is_entry = path.replace("\\", "/").endswith(ENTRY_SCRIPT)
    for index, token in enumerate(tokens):
        if token.kind != "name":
            continue
        previous = tokens[index - 1] if index else None
        # `obj.game` and `obj:game()` are fields, not the global.
        if previous is not None and previous.kind == "op" and previous.text in (".", ":"):
            continue
        if token.text == SCRIPT_GLOBAL and index not in in_require:
            following = tokens[index + 1 : index + 3]
            reaches_parent_only = (len(following) == 2 and following[0].text == "."
                                   and following[1].text == "Parent")
            if not (is_entry and reaches_parent_only):
                found.append(violation(token.offset, "untyped-script", SCRIPT_MESSAGE))
        elif token.text in FORBIDDEN_GLOBALS:
            found.append(violation(token.offset, "forbidden-global",
                                   f"`{token.text}`: {FORBIDDEN_GLOBALS[token.text]}"))
        elif (token.text == "require" and len(tokens) > index + 2
              and tokens[index + 1].text == "(" and tokens[index + 2].kind == "number"):
            found.append(violation(token.offset, "asset-require",
                                   "require by asset id loads unreviewed remote code (a common backdoor)"))

    if path.replace("\\", "/").startswith(CLIENT_ROOT):
        for span in require_spans(tokens):
            climbs = [i for i in span if tokens[i].kind == "name" and tokens[i].text == "Parent"]
            if len(climbs) > 1:
                found.append(violation(tokens[climbs[1]].offset, "client-require-escapes",
                                       CLIENT_REQUIRE_MESSAGE))
    return found


def render_services_module(services: set[str] | list[str]) -> str:
    """The one file allowed to touch `game`, rendered from a list of names.

    `DataModel` is accepted alongside the services and emitted as a cast of
    `game` itself. It is not a service, but some of what a server needs lives
    only on the DataModel, and `BindToClose` is the one the engineer cannot do
    without: the standards it is given require saving there, and every other
    route to it is banned. Six attempts of a real run died on that line, which
    is the model obeying one rule and breaking another it had no way to keep.

    The cast is what makes it safe, measured rather than assumed:

        local dm = game :: DataModel
        dm:BindToClose(function() end)   -- accepted, a real method
        dm:MadeUpMethod()                -- rejected, Key not found in DataModel

    Only the bare global is untyped. Named and cast, it is checked like
    anything else.
    """
    names = sorted(set(services))
    if not names:
        return SERVICES_HEADER + "return {}\n"
    body = "".join(
        f"\t{DATAMODEL_NAME} = game :: {DATAMODEL_NAME},\n" if name == DATAMODEL_NAME
        else f'\t{name} = game:GetService("{name}") :: {name},\n'
        for name in names
    )
    return SERVICES_HEADER + "return {\n" + body + "}\n"


def check_services_module(source: str, path: str, known_services: frozenset[str]) -> list[Violation]:
    """The one file allowed to touch `game` must be exactly generator output."""
    names: list[str] = []
    for line in source.splitlines():
        match = _SERVICE_LINE.match(line) or _DATAMODEL_LINE.match(line)
        if match:
            names.append(match.group(1))
    found = [
        Violation(path, 1, 1, "unknown-service", f"`{name}` is not a Roblox service")
        for name in sorted(set(names))
        # DataModel is deliberately not in the service list: it is a class, not
        # a service, and the API dump does not tag it as one.
        if name != DATAMODEL_NAME and name not in known_services
    ]
    if source != render_services_module(names):
        found.append(Violation(path, 1, 1, "services-module-edited",
                               "Services module differs from generator output; regenerate it instead of editing"))
    return found


def check_project(src_root: Path, services_module: Path | tuple[Path, ...],
                  known_services: frozenset[str]) -> list[Violation]:
    """Every Luau file under `src_root`, reported relative to it.

    More than one generated Services module is allowed -- the client gets its
    own copy, because it cannot reach the shared one at run time -- and each is
    held to the same byte-identity check.
    """
    modules = (services_module,) if isinstance(services_module, Path) else tuple(services_module)
    generated = {module.resolve() for module in modules}
    found: list[Violation] = []
    for file in sorted(p for p in src_root.rglob("*") if p.suffix in (".luau", ".lua") and p.is_file()):
        relative = file.relative_to(src_root).as_posix()
        # Bytes, decoded without newline translation: the Services module's
        # identity check is byte-exact, and a CRLF or BOM copy must not pass it.
        source = file.read_bytes().decode("utf-8", "replace")
        if file.resolve() in generated:
            found.extend(check_services_module(source, relative, known_services))
        else:
            found.extend(check_source(source, relative))
    return found
