"""Blueprint -> GameBuildSpecification.

Deterministic on purpose: no model runs here. The specification is the contract
between what the user approved and what the Engineer builds, so it is derived
from the blueprint by rules a person can read, not generated by something that
could quietly add a system nobody asked for.

Two refusals are the point of the module. A blueprint that is not ready does
not compile, and a system whose dependency is not in the build does not compile
-- shipping a spec that references a system nobody will build is how a build
fails halfway through with a confusing error instead of before it starts.
"""

from __future__ import annotations

import secrets

from .readiness import assess
from .schemas import (
    Blueprint,
    BuildTarget,
    GameBuildSpecification,
    Persistence,
    Platform,
    Scope,
    SpecSystem,
    SystemLayer,
)

LAYER_ROOT: dict[SystemLayer, str] = {
    SystemLayer.SERVER: "src/server",
    SystemLayer.CLIENT: "src/client",
    SystemLayer.SHARED: "src/shared",
}

SCOPE_CONSTRAINT: dict[Scope, str] = {
    Scope.QUICK_PROTOTYPE: "Prototype scope: the smallest thing that demonstrates the loop.",
    Scope.VERTICAL_SLICE: "Vertical slice: one complete path through the loop, properly built.",
    Scope.EXPANDED_PROTOTYPE: "Expanded prototype: the loop plus its supporting systems.",
}


class NotReady(ValueError):
    """The blueprint cannot be built yet; the message names what is missing."""


def _constraints(blueprint: Blueprint) -> list[str]:
    """Constraints the Engineer must obey, phrased as prohibitions where they are.

    The persistence line is the important one: "no DataStore" has to be a
    constraint the Engineer reads, not an absence it might fill in helpfully.
    """
    config = blueprint.config
    constraints = [SCOPE_CONSTRAINT[config.scope]]
    if config.persistence is Persistence.SESSION_ONLY:
        constraints.append(
            "NO DATASTORE. Progress lasts one session; do not write DataStore code, "
            "do not add saving, and do not add a session lock.")
    else:
        constraints.append(
            "Progress is saved: use DataStoreService through the generated Services module, "
            "with bounded retries and a session lock.")
    if config.max_players == 1:
        constraints.append("Single player: no multiplayer coordination, no per-player contention.")
    else:
        constraints.append(f"Up to {config.max_players} players in one server; "
                           "never assume a fixed number of players.")
    if Platform.MOBILE in config.platforms:
        constraints.append("Mobile is a target: no keyboard-only input path.")
    if config.build_target is BuildTarget.CURRENT_PLACE:
        constraints.append(
            "Building into an existing place: inspect what is there first and never replace "
            "Workspace, ReplicatedStorage, StarterGui or ServerScriptService wholesale.")
    return constraints


def _ordered(systems: list, index: dict[str, SpecSystem]) -> list[str]:
    """Build order: dependencies before dependents, stable otherwise.

    A cycle cannot be ordered, so it is reported rather than broken arbitrarily
    -- picking a side silently would produce a build that fails for a reason
    nobody could trace back to here.
    """
    order: list[str] = []
    placed: set[str] = set()
    visiting: set[str] = set()

    def place(name: str, trail: tuple[str, ...]) -> None:
        if name in placed:
            return
        if name in visiting:
            raise NotReady("these systems depend on each other in a circle, so there is no "
                           f"order to build them in: {' -> '.join([*trail, name])}")
        visiting.add(name)
        for dependency in index[name].depends_on:
            if dependency in index:
                place(dependency, (*trail, name))
        visiting.discard(name)
        placed.add(name)
        order.append(name)

    for system in systems:
        place(system.name, ())
    return order


def compile_spec(blueprint: Blueprint, *, spec_id: str | None = None,
                 revision: int | None = None) -> GameBuildSpecification:
    """The specification the Engineer is handed, or a refusal saying why not."""
    readiness = assess(blueprint)
    if not readiness.ready:
        missing = "; ".join(requirement.prompt for requirement in readiness.missing)
        raise NotReady(f"this blueprint is {readiness.percent}% ready: {missing}")

    active = blueprint.active_systems()
    systems: list[SpecSystem] = []
    for system in active:
        root = LAYER_ROOT[system.layer]
        systems.append(SpecSystem(
            name=system.name, layer=system.layer, path=f"{root}/{system.name}.luau",
            purpose=system.purpose, acceptance_criteria=list(system.acceptance_criteria),
            depends_on=list(system.depends_on), builds_world=system.builds_world))

    index = {system.name: system for system in systems}
    unknown = sorted({dependency for system in systems for dependency in system.depends_on
                      if dependency not in index})
    if unknown:
        raise NotReady(
            "these systems are depended on but are not in the build: " + ", ".join(unknown)
            + ". Add them, or remove the dependency.")

    duplicates = sorted({system.name for system in systems
                         if sum(1 for other in systems if other.name == system.name) > 1})
    if duplicates:
        raise NotReady("two systems share a name, so one would overwrite the other: "
                       + ", ".join(duplicates))

    criteria = [f"{system.name}: {criterion}"
                for system in systems for criterion in system.acceptance_criteria]

    spec = GameBuildSpecification(
        spec_id=spec_id or secrets.token_hex(8),
        revision=revision if revision is not None else blueprint.revision,
        project_id=blueprint.project_id,
        blueprint_id=blueprint.id,
        idea_id=blueprint.audit_id,
        title=blueprint.title,
        summary=blueprint.summary,
        core_loop=blueprint.user_intent[:2000],
        config=blueprint.config,
        systems=systems,
        build_order=_ordered(systems, index),
        included_features=[feature.title for feature in blueprint.selected_features()],
        excluded_features=[feature.title for feature in blueprint.rejected_features()],
        asset_requirements=list(blueprint.asset_requirements),
        technical_constraints=_constraints(blueprint),
        acceptance_criteria=criteria,
    )
    return spec.model_copy(update={"content_hash": spec.fingerprint()})


def human_preview(spec: GameBuildSpecification) -> dict:
    """What the Engineer will build, for a person rather than for a parser.

    Counts come from the specification itself, so the preview cannot drift from
    what is actually about to be built (section 13).
    """
    by_layer: dict[str, list[str]] = {"server": [], "client": [], "shared": []}
    for system in spec.systems:
        by_layer[system.layer.value].append(system.name)
    weight = len(spec.systems) + sum(len(system.depends_on) for system in spec.systems)
    complexity = "low" if weight <= 6 else "medium" if weight <= 18 else "high"
    return {
        "title": spec.title,
        "players": f"{spec.config.min_players}-{spec.config.max_players}",
        "world": spec.config.world.value,
        "scope": spec.config.scope.value,
        "persistence": spec.config.persistence.value,
        "core_loop": spec.core_loop,
        "systems_total": len(spec.systems),
        "server_systems": by_layer["server"],
        "client_systems": by_layer["client"],
        "shared_systems": by_layer["shared"],
        "build_order": spec.build_order,
        "included_features": spec.included_features,
        "excluded_features": spec.excluded_features,
        "asset_requirements": spec.asset_requirements,
        "technical_constraints": spec.technical_constraints,
        "acceptance_criteria_count": len(spec.acceptance_criteria),
        "estimated_complexity": complexity,
    }
